name: CI Pipeline

on:
  push:
    branches: ["**"]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Config Environment
        uses: actions/setup-node@v3
        with:
          node-version: ">=18.17"

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: TS Lint
        run: pnpm lint

      - name: Build
        run: pnpm build
